const SERVICE_SEGMENTS = ["Mujer", "Hombre", "Nino"];

const CAROUSEL_BG_OPTIONS = [
  "from-rose-400 to-violet-500",
  "from-violet-400 to-rose-400",
  "from-amber-400 to-rose-400",
  "from-rose-500 to-violet-600",
  "from-cyan-400 to-blue-500",
  "from-emerald-400 to-teal-500",
];

const DEFAULT_PRODUCT_CATEGORIES = [
  {
    nombre: "Necesidades",
    estado: "Activa",
    descripcion: "Categorias de necesidades capilares.",
  },
  {
    nombre: "Cabello",
    estado: "Activa",
    descripcion: "Lineas para cuidado integral del cabello.",
  },
  {
    nombre: "Mondo Verde",
    estado: "Activa",
    descripcion: "Alternativas de cuidado sustentable.",
  },
  {
    nombre: "Piel",
    estado: "Activa",
    descripcion: "Productos para cuidado de piel.",
  },
  {
    nombre: "Maquillaje",
    estado: "Activa",
    descripcion: "Catalogo de maquillaje profesional.",
  },
];

const DEFAULT_PRODUCT_BRANDS = [
  {
    nombre: "Avyna",
    pais: "Mexico",
    estado: "Activa",
    descripcion: "Marca principal del catalogo.",
  },
  {
    nombre: "Wella",
    pais: "Alemania",
    estado: "Activa",
    descripcion: "Linea profesional para coloracion.",
  },
  {
    nombre: "Loreal Professionnel",
    pais: "Francia",
    estado: "Inactiva",
    descripcion: "Marca disponible por temporadas.",
  },
];

const DEFAULT_PRODUCTS = [
  {
    nombre: "Shampoo AVYNA Nutritivo",
    marca: "Avyna",
    precio: 220,
    stock: 20,
    categoria: "Necesidades",
    descripcion: "Limpieza suave y nutricion para uso diario.",
    imagen: "",
    imagenNombre: "",
    rating: 4.9,
  },
  {
    nombre: "Mascarilla AVYNA Reparadora",
    marca: "Avyna",
    precio: 280,
    stock: 15,
    categoria: "Necesidades",
    descripcion: "Repara y fortalece la fibra capilar.",
    imagen: "",
    imagenNombre: "",
    rating: 4.8,
  },
  {
    nombre: "Aceite AVYNA Brillo",
    marca: "Avyna",
    precio: 190,
    stock: 30,
    categoria: "Cabello",
    descripcion: "Control de frizz y brillo inmediato.",
    imagen: "",
    imagenNombre: "",
    rating: 4.7,
  },
  {
    nombre: "Spray AVYNA Termoprotector",
    marca: "Avyna",
    precio: 210,
    stock: 18,
    categoria: "Necesidades",
    descripcion: "Proteccion termica para plancha y secadora.",
    imagen: "",
    imagenNombre: "",
    rating: 4.8,
  },
  {
    nombre: "Shampoo Ialuronico",
    marca: "Avyna",
    precio: 240,
    stock: 12,
    categoria: "Cabello",
    descripcion: "Hidratacion profunda para cabello seco.",
    imagen: "",
    imagenNombre: "",
    rating: 4.9,
  },
  {
    nombre: "Labial Matte",
    marca: "Avyna",
    precio: 150,
    stock: 25,
    categoria: "Maquillaje",
    descripcion: "Acabado mate de larga duracion.",
    imagen: "",
    imagenNombre: "",
    rating: 4.5,
  },
];

const DEFAULT_SERVICE_CATEGORIES = [
  { nombre: "Cortes", segmento: "Mujer", estado: "Activa", descripcion: "Cortes para mujer." },
  { nombre: "Cejas y Pestanas", segmento: "Mujer", estado: "Activa", descripcion: "Diseno y cuidado de cejas y pestanas." },
  { nombre: "Coloracion y Tratamientos", segmento: "Mujer", estado: "Activa", descripcion: "Coloracion y tratamientos capilares." },
  { nombre: "Unas", segmento: "Mujer", estado: "Activa", descripcion: "Servicios para unas." },
  { nombre: "Peinado", segmento: "Mujer", estado: "Activa", descripcion: "Peinados para distintas ocasiones." },
  { nombre: "Cortes", segmento: "Hombre", estado: "Activa", descripcion: "Cortes para hombre." },
  { nombre: "Cortes", segmento: "Nino", estado: "Activa", descripcion: "Cortes para nino." },
];

const DEFAULT_SERVICES = [
  {
    nombre: "Corte en Capas",
    segmento: "Mujer",
    subcategoria: "Cortes",
    precio: 280,
    tiempo: "40-50 min",
    descripcion: "Corte con movimiento y volumen natural.",
    imagen: "",
    imagenNombre: "",
  },
  {
    nombre: "Corte Bob",
    segmento: "Mujer",
    subcategoria: "Cortes",
    precio: 300,
    tiempo: "45-55 min",
    descripcion: "Estilo bob clasico con terminacion pulida.",
    imagen: "",
    imagenNombre: "",
  },
  {
    nombre: "Planchado de Ceja",
    segmento: "Mujer",
    subcategoria: "Cejas y Pestanas",
    precio: 250,
    tiempo: "30-40 min",
    descripcion: "Definicion y fijacion de cejas.",
    imagen: "",
    imagenNombre: "",
  },
  {
    nombre: "Lifting de Pestanas",
    segmento: "Mujer",
    subcategoria: "Cejas y Pestanas",
    precio: 380,
    tiempo: "45-60 min",
    descripcion: "Elevacion natural de pestanas.",
    imagen: "",
    imagenNombre: "",
  },
  {
    nombre: "Aplicacion de Tinte",
    segmento: "Mujer",
    subcategoria: "Coloracion y Tratamientos",
    precio: 700,
    tiempo: "90-120 min",
    descripcion: "Color uniforme con acabado profesional.",
    imagen: "",
    imagenNombre: "",
  },
  {
    nombre: "Manicure",
    segmento: "Mujer",
    subcategoria: "Unas",
    precio: 220,
    tiempo: "30-40 min",
    descripcion: "Limpieza y cuidado completo de unas.",
    imagen: "",
    imagenNombre: "",
  },
  {
    nombre: "Pedicure",
    segmento: "Mujer",
    subcategoria: "Unas",
    precio: 260,
    tiempo: "40-50 min",
    descripcion: "Cuidado estetico y relajante para pies.",
    imagen: "",
    imagenNombre: "",
  },
  {
    nombre: "Planchado",
    segmento: "Mujer",
    subcategoria: "Peinado",
    precio: 240,
    tiempo: "30-45 min",
    descripcion: "Alisado temporal con acabado brillante.",
    imagen: "",
    imagenNombre: "",
  },
  {
    nombre: "Corte Clasico",
    segmento: "Hombre",
    subcategoria: "Cortes",
    precio: 180,
    tiempo: "25-35 min",
    descripcion: "Corte tradicional limpio y uniforme.",
    imagen: "",
    imagenNombre: "",
  },
  {
    nombre: "Corte Fade Bajo",
    segmento: "Hombre",
    subcategoria: "Cortes",
    precio: 220,
    tiempo: "30-40 min",
    descripcion: "Degradado bajo con transicion suave.",
    imagen: "",
    imagenNombre: "",
  },
  {
    nombre: "Corte Escolar",
    segmento: "Nino",
    subcategoria: "Cortes",
    precio: 150,
    tiempo: "20-30 min",
    descripcion: "Corte practico para uso escolar.",
    imagen: "",
    imagenNombre: "",
  },
  {
    nombre: "Corte Tipo Spiky",
    segmento: "Nino",
    subcategoria: "Cortes",
    precio: 170,
    tiempo: "25-35 min",
    descripcion: "Textura en puntas para estilo juvenil.",
    imagen: "",
    imagenNombre: "",
  },
];

const DEFAULT_COMPANY_INFO = {
  key: "main",
  nombre: "Estetica Panamericana",
  direccion: "Av. Principal #123, Ciudad",
  telefono: "555-1234",
  email: "contacto@estetica.com",
  mision: "Brindar servicios de belleza de la mas alta calidad.",
  vision: "Ser la estetica lider en la region.",
  valores: "Compromiso, Calidad, Higiene",
  facebook: "facebook.com/estetica",
  instagram: "instagram.com/estetica",
  quienesSomosTexto:
    "En Estetica Panamericana combinamos pasion, profesionalismo y productos de calidad para realzar tu belleza.",
  quienesSomosEsencia:
    "Atencion personalizada\nEstilistas certificados\nExperiencia premium\nProductos profesionales AVYNA",
  horarioLunesSabado: "Lunes a Sabado: 9:00 am - 7:00 pm",
  horarioDomingo: "Domingo: 10:00 am - 3:00 pm",
  mapLat: "19.4326",
  mapLng: "-99.1332",
  mapZoom: "15",
  mapGoogleUrl: "https://www.google.com/maps?q=19.4326,-99.1332",
  politicasDocumento: "",
  politicasDocumentoNombre: "",
  politicasDocumentoTipo: "",
};

const DEFAULT_CAROUSEL_SLIDES = [
  {
    title: "Transformaciones Increibles",
    description: "Nuestros estilistas certificados crean magia con cada corte",
    image: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=1200&h=600&fit=crop",
    bgColor: "from-rose-400 to-violet-500",
    estado: "Activa",
    orden: 0,
  },
  {
    title: "Productos AVYNA Premium",
    description: "Linea profesional para un cuidado excepcional del cabello",
    image: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=1200&h=600&fit=crop",
    bgColor: "from-violet-400 to-rose-400",
    estado: "Activa",
    orden: 1,
  },
  {
    title: "Ambiente Relajante",
    description: "Disfruta de una experiencia premium en cada visita",
    image: "https://images.unsplash.com/photo-1562322140-8baeececf3df?w=1200&h=600&fit=crop",
    bgColor: "from-amber-400 to-rose-400",
    estado: "Activa",
    orden: 2,
  },
  {
    title: "Tendencias Actuales",
    description: "Siempre a la vanguardia de la moda y estilo",
    image: "https://images.unsplash.com/photo-1633681926022-84c23e8cb2d6?w=1200&h=600&fit=crop",
    bgColor: "from-rose-500 to-violet-600",
    estado: "Activa",
    orden: 3,
  },
];

const DEFAULT_STAFF_MEMBERS = [
  {
    nombre: "Ana Martinez",
    rol: "Administrador",
    email: "ana@estetica.com",
    telefono: "5550101",
    estado: "Activo",
  },
  {
    nombre: "Carlos Ruiz",
    rol: "Estilista",
    email: "carlos@estetica.com",
    telefono: "5550102",
    estado: "Activo",
  },
  {
    nombre: "Lucia Gomez",
    rol: "Recepcionista",
    email: "lucia@estetica.com",
    telefono: "5550103",
    estado: "Inactivo",
  },
];

module.exports = {
  SERVICE_SEGMENTS,
  CAROUSEL_BG_OPTIONS,
  DEFAULT_PRODUCT_CATEGORIES,
  DEFAULT_PRODUCT_BRANDS,
  DEFAULT_PRODUCTS,
  DEFAULT_SERVICE_CATEGORIES,
  DEFAULT_SERVICES,
  DEFAULT_COMPANY_INFO,
  DEFAULT_CAROUSEL_SLIDES,
  DEFAULT_STAFF_MEMBERS,
};
